name: Cross Compile Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target: [x86_64-unknown-linux-gnu, x86_64-apple-darwin, x86_64-pc-windows-msvc, aarch64-apple-darwin]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        target: ${{ matrix.target }}
        override: true
      
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release serve --target ${{ matrix.target }}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.target }}
        path: target/${{ matrix.target }}/release/serve
