name: Cross Compile Code

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        target: [aarch64-apple-darwin]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        target: ${{ matrix.target }}
        override: true
      
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release serve --target ${{ matrix.target }}
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.target }}
        path: target/${{ matrix.target }}/release/serve
