name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Check for Linting Issues
        run: |
          rustup component add clippy
          cargo clippy -- -D warnings
        
      - name: Check Code Formatting
        run: |
          rustup component add rustfmt
          cargo fmt -- --check
      
      - name: Run Tests
        run: cargo test